[package]
name = "grade_gen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argparse = "0.2.2"
simple_excel_writer="0.1.9"
dirs = "4.0"
office = "0.8.1"
