blank_lines_lower_bound      = 1
blank_lines_upper_bound      = 2
brace_style                  = "PreferSameLine"
chain_width                  = 80
color                        = "Always"
combine_control_expr         = false
comment_width                = 70
condense_wildcard_suffixes   = false            # Reason. Not stable
control_brace_style          = "AlwaysSameLine"
edition                      = "2021"
empty_item_single_line       = true
enum_discrim_align_threshold = 80
error_on_line_overflow       = true
error_on_unformatted         = true
fn_args_layout               = "Tall"
fn_single_line               = false
format_code_in_doc_comments  = true
format_strings               = true
imports_granularity          = "Module"
imports_indent               = "Block"
imports_layout               = "Mixed"
indent_style                 = "Block"
# license_template_path           = "LICENSE"  TODO: how does this work?
group_imports                = "StdExternalCrate"
match_arm_leading_pipes      = "Never"            # "Always"
max_width                    = 120
merge_derives                = true
newline_style                = "Unix"
normalize_comments           = true
normalize_doc_attributes     = true
reorder_impl_items           = true
reorder_imports              = true
reorder_modules              = true
space_after_colon            = true
space_before_colon           = false
spaces_around_ranges         = false
struct_field_align_threshold = 80
struct_lit_single_line       = true
tab_spaces                   = 4
trailing_comma               = "Never"
trailing_semicolon           = true
type_punctuation_density     = "Wide"
unstable_features            = true               #Stays false till strictly necessary
use_field_init_shorthand     = true               # As a note, this mixes the short-hand with normal 
wrap_comments                = true
