binop_separator              = "Front"
blank_lines_lower_bound      = 1
blank_lines_upper_bound      = 2
brace_style                  = "PreferSameLine"
chain_width                  = 100
color                        = "Always"
combine_control_expr         = false
comment_width                = 100
condense_wildcard_suffixes   = false              # Reason. Not stable
control_brace_style          = "AlwaysSameLine"
edition                      = "2021"
empty_item_single_line       = true
enum_discrim_align_threshold = 30
error_on_line_overflow       = true
error_on_unformatted         = true
fn_args_layout               = "Compressed"
fn_call_width                = 80
fn_single_line               = true
force_explicit_abi           = true
force_multiline_blocks       = true
format_code_in_doc_comments  = true
format_macro_bodies          = true
format_strings               = true
group_imports                = "StdExternalCrate"
hard_tabs                    = false
hex_literal_case             = "Upper"
imports_granularity          = "Module"
imports_indent               = "Visual"
imports_layout               = "Mixed"
indent_style                 = "Block"
inline_attribute_width       = 60
match_arm_leading_pipes      = "Never"
match_block_trailing_comma   = true
max_width                    = 100
merge_derives                = true
newline_style                = "Unix"
normalize_comments           = true
normalize_doc_attributes     = true
overflow_delimited_expr      = true
remove_nested_parens         = true
reorder_impl_items           = true
reorder_imports              = true
reorder_modules              = true
report_fixme                 = "Always"
report_todo                  = "Always"
space_after_colon            = true
space_before_colon           = true
spaces_around_ranges         = true
struct_field_align_threshold = 30
struct_lit_single_line       = true
tab_spaces                   = 4
trailing_comma               = "Never"
trailing_semicolon           = true
type_punctuation_density     = "Wide"
unstable_features            = true               #Stays false till strictly necessary
use_field_init_shorthand     = true               # As a note, this mixes the short-hand with normal 
use_small_heuristics         = "Max"
use_try_shorthand            = false
where_single_line            = true
wrap_comments                = true
