name: Rust

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Build
        run: cargo build --all --release && strip target/release/canvas2camu

      - name: Package
        run: zip -r -9 canvas2camu_linux.zip target/release/canvas2camu

      - name: Upload Package
        uses: actions/upload-artifact@v3
        with:
          name: canvas2camu_linux
          path: canvas2camu_linux.zip
          if-no-files-found: error 

  build-win:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Build
        run: cargo build --all --release

      - name: Package
        run: Compress-Archive -LiteralPath 'target/release/canvas2camu.exe' -DestinationPath 'canvas2camu_win.zip'

      - name: Upload Package
        uses: actions/upload-artifact@v3
        with:
          name: canvas2camu_win
          path: canvas2camu_win.zip
          if-no-files-found: error 

  build-mac:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-apple-darwin
          default: true
          override: true

      - name: Build for mac
        run: cargo build --all --release && strip target/release/canvas2camu

      - name: Package
        run: zip -r -9 canvas2camu_darwin.zip target/release/canvas2camu

      - name: Upload Package
        uses: actions/upload-artifact@v3
        with:
          name: canvas2camu_darwin
          path: canvas2camu_darwin.zip
          if-no-files-found: error 

  get_project_version:
    if: github.repository == 'ianakotey/canvas2camu-rs'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Extract cargo version
        run: sed -n '/^version/s/version\s*=\s*//p'  Cargo.toml | sed 's/"//g'` > version.txt

      - name: Upload version information
        uses: actions/upload-artifact@v3
        with:
          name: version
          path: version.txt
          if-no-files-found: error


  release:
    if: github.repository == 'ianakotey/canvas2camu-rs'
    needs: [build-linux, build-mac, build-win, get_project_version]
    runs-on: ubuntu-latest
    steps:
      - name: Download all packages
        uses: actions/download-artifact@v3

      - name: Display structure of downloaded files
        run: ls -R

      - name: Get version of cargo project
        run: export CARGO_VERSION=`cat version/version.txt` 

      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ CARGO_VERSION }}
          draft: true
          files: |
            canvas2camu_linux/canvas2camu_linux.zip
            canvas2camu_win/canvas2camu_win.zip
            canvas2camu_darwin/canvas2camu_darwin.zip
